version: 2
updates:
  # Node.js dependencies (package.json / package-lock.json)
  - package-ecosystem: "npm"
    directory: "/" # adjust if package.json is inside a subfolder
    schedule:
      interval: "weekly"

  # Maven dependencies (pom.xml for Java services)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

  # Go dependencies (go.mod)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker dependencies (Dockerfiles)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
