# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-app
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/M-Samii/microservices-demo.git
#     targetRevision: HEAD
#     path: helm-chart/templates
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated: {}

##########################################################################

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-app
#   namespace: argocd
#   annotations:
#   # Argo CD Image Updater settings
#     argocd-image-updater.argoproj.io/write-back-method: argocd
#     argocd-image-updater.argoproj.io/service1.allow-tags: latest
#     argocd-image-updater.argoproj.io/service2.allow-tags: latest
#     argocd-image-updater.argoproj.io/service3.allow-tags: latest  
#     argocd-image-updater.argoproj.io/service4.allow-tags: latest
#     argocd-image-updater.argoproj.io/service5.allow-tags: latest
#     argocd-image-updater.argoproj.io/service6.allow-tags: latest
#     argocd-image-updater.argoproj.io/service7.allow-tags: latest
#     argocd-image-updater.argoproj.io/service8.allow-tags: latest
#     argocd-image-updater.argoproj.io/service9.allow-tags: latest
#     argocd-image-updater.argoproj.io/service10.allow-tags: latest
#     argocd-image-updater.argoproj.io/service11.allow-tags: latest
    


#     argocd-image-updater.argoproj.io/image-list: |
#       service1=mahsamii/adservice,
#       service2=mahsamii/cartservice,
#       service3=mahsamii/checkoutservice,
#       service4=mahsamii/currencyservice,  
#       service5=mahsamii/emailservice,
#       service6=mahsamii/frontend,
#       service7=mahsamii/loadgenerator,
#       service8=mahsamii/paymentservice,
#       service9=mahsamii/productcatalogservice,
#       service10=mahsamii/recommendationservice,
#       service11=mahsamii/shippingservice
#     argocd-image-updater.argoproj.io/service1.update-strategy: digest
#     argocd-image-updater.argoproj.io/service2.update-strategy: digest
#     argocd-image-updater.argoproj.io/service3.update-strategy: digest
#     argocd-image-updater.argoproj.io/service4.update-strategy: digest
#     argocd-image-updater.argoproj.io/service5.update-strategy: digest
#     argocd-image-updater.argoproj.io/service6.update-strategy: digest
#     argocd-image-updater.argoproj.io/service7.update-strategy: digest
#     argocd-image-updater.argoproj.io/service8.update-strategy: digest
#     argocd-image-updater.argoproj.io/service9.update-strategy: digest
#     argocd-image-updater.argoproj.io/service10.update-strategy: digest
#     argocd-image-updater.argoproj.io/service11.update-strategy: digest
   
    

# spec:
#   project: default
#   source:
#     repoURL: https://github.com/M-Samii/microservices-demo.git
#     targetRevision: HEAD
#     path: helm-chart  
#     helm:
#       valueFiles:
#         - values.yaml  
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated: {}


#################################
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-app
#   namespace: argocd
#   annotations:
#     # Argo CD Image Updater settings
#     argocd-image-updater.argoproj.io/write-back-method: argocd
#     argocd-image-updater.argoproj.io/image-list: |
#       service1=mahsamii/adservice
#       service2=mahsamii/cartservice
#       service3=mahsamii/checkoutservice
#       service4=mahsamii/currencyservice
#       service5=mahsamii/emailservice
#       service6=mahsamii/frontend
#       service7=mahsamii/loadgenerator
#       service8=mahsamii/paymentservice
#       service9=mahsamii/productcatalogservice
#       service10=mahsamii/recommendationservice
#       service11=mahsamii/shippingservice
#     argocd-image-updater.argoproj.io/service1.allow-tags: latest
#     argocd-image-updater.argoproj.io/service1.update-strategy: digest
#     argocd-image-updater.argoproj.io/service2.allow-tags: latest
#     argocd-image-updater.argoproj.io/service2.update-strategy: digest
#     argocd-image-updater.argoproj.io/service3.allow-tags: latest
#     argocd-image-updater.argoproj.io/service3.update-strategy: digest
#     argocd-image-updater.argoproj.io/service4.allow-tags: latest
#     argocd-image-updater.argoproj.io/service4.update-strategy: digest
#     argocd-image-updater.argoproj.io/service5.allow-tags: latest
#     argocd-image-updater.argoproj.io/service5.update-strategy: digest
#     argocd-image-updater.argoproj.io/service6.allow-tags: latest
#     argocd-image-updater.argoproj.io/service6.update-strategy: digest
#     argocd-image-updater.argoproj.io/service7.allow-tags: latest
#     argocd-image-updater.argoproj.io/service7.update-strategy: digest
#     argocd-image-updater.argoproj.io/service8.allow-tags: latest
#     argocd-image-updater.argoproj.io/service8.update-strategy: digest
#     argocd-image-updater.argoproj.io/service9.allow-tags: latest
#     argocd-image-updater.argoproj.io/service9.update-strategy: digest
#     argocd-image-updater.argoproj.io/service10.allow-tags: latest
#     argocd-image-updater.argoproj.io/service10.update-strategy: digest
#     argocd-image-updater.argoproj.io/service11.allow-tags: latest
#     argocd-image-updater.argoproj.io/service11.update-strategy: digest
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/M-Samii/microservices-demo.git
#     targetRevision: HEAD
#     path: helm-chart
#     helm:
#       valueFiles:
#         - values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

###############################################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: "service1=mahsamii/adservice:latest"
    argocd-image-updater.argoproj.io/service1.update-strategy: digest
    argocd-image-updater.argoproj.io/service1.helm.image-digest: adService.image.digest

spec:
  project: default
  source:
    repoURL: https://github.com/M-Samii/microservices-demo.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    # syncOptions:
    #   - ResourceHooks=true 
    #   - Validate=true
    #   - CreateNamespace=true
    #   - PruneLast=true
    #   - ApplyOutOfSyncOnly=true
    #   - Replace=true
    #   - SkipDryRunOnMissingResource=true
    #   - EnableAlphaFeatures=true



##############################################################











# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-app
#   namespace: argocd
#   annotations:
#     argocd-image-updater.argoproj.io/write-back-method: argocd
#     argocd-image-updater.argoproj.io/image-list: "service1=mahsamii/adservice:latest,service2=mahsamii/cartservice,service3=mahsamii/checkoutservice,service4=mahsamii/currencyservice,service5=mahsamii/emailservice,service6=mahsamii/frontend,service8=mahsamii/paymentservice,service9=mahsamii/productcatalogservice,service10=mahsamii/recommendationservice,service11=mahsamii/shippingservice"

#     argocd-image-updater.argoproj.io/service1.allow-tags: latest
#     argocd-image-updater.argoproj.io/service1.update-strategy: digest
#     argocd-image-updater.argoproj.io/service1.helm-image-name: adService.name
#     argocd-image-updater.argoproj.io/service1.helm-tag-name: image.tag

#     argocd-image-updater.argoproj.io/service2.allow-tags: latest
#     argocd-image-updater.argoproj.io/service2.update-strategy: digest
#     argocd-image-updater.argoproj.io/service2.helm-image-name: cartService.image.repository
#     argocd-image-updater.argoproj.io/service2.helm-tag-name: cartService.image.tag

#     argocd-image-updater.argoproj.io/service3.allow-tags: latest
#     argocd-image-updater.argoproj.io/service3.update-strategy: digest
#     argocd-image-updater.argoproj.io/service3.helm-image-name: checkoutService.image.repository
#     argocd-image-updater.argoproj.io/service3.helm-tag-name: checkoutService.image.tag

#     argocd-image-updater.argoproj.io/service4.allow-tags: latest
#     argocd-image-updater.argoproj.io/service4.update-strategy: digest
#     argocd-image-updater.argoproj.io/service4.helm-image-name: currencyService.image.repository
#     argocd-image-updater.argoproj.io/service4.helm-tag-name: currencyService.image.tag

#     argocd-image-updater.argoproj.io/service5.allow-tags: latest
#     argocd-image-updater.argoproj.io/service5.update-strategy: digest
#     argocd-image-updater.argoproj.io/service5.helm-image-name: emailService.image.repository
#     argocd-image-updater.argoproj.io/service5.helm-tag-name: emailService.image.tag

#     argocd-image-updater.argoproj.io/service6.allow-tags: latest
#     argocd-image-updater.argoproj.io/service6.update-strategy: digest
#     argocd-image-updater.argoproj.io/service6.helm-image-name: frontend.image.repository
#     argocd-image-updater.argoproj.io/service6.helm-tag-name: frontend.image.tag

#     argocd-image-updater.argoproj.io/service7.allow-tags: latest
#     argocd-image-updater.argoproj.io/service7.update-strategy: digest
#     argocd-image-updater.argoproj.io/service7.helm-image-name: loadGenerator.image.repository
#     argocd-image-updater.argoproj.io/service7.helm-tag-name: loadGenerator.image.tag

#     argocd-image-updater.argoproj.io/service8.allow-tags: latest
#     argocd-image-updater.argoproj.io/service8.update-strategy: digest
#     argocd-image-updater.argoproj.io/service8.helm-image-name: paymentService.image.repository
#     argocd-image-updater.argoproj.io/service8.helm-tag-name: paymentService.image.tag

#     argocd-image-updater.argoproj.io/service9.allow-tags: latest
#     argocd-image-updater.argoproj.io/service9.update-strategy: digest
#     argocd-image-updater.argoproj.io/service9.helm-image-name: productCatalogService.image.repository
#     argocd-image-updater.argoproj.io/service9.helm-tag-name: productCatalogService.image.tag

#     argocd-image-updater.argoproj.io/service10.allow-tags: latest
#     argocd-image-updater.argoproj.io/service10.update-strategy: digest
#     argocd-image-updater.argoproj.io/service10.helm-image-name: recommendationService.image.repository
#     argocd-image-updater.argoproj.io/service10.helm-tag-name: recommendationService.image.tag

#     argocd-image-updater.argoproj.io/service11.allow-tags: latest
#     argocd-image-updater.argoproj.io/service11.update-strategy: digest
#     argocd-image-updater.argoproj.io/service11.helm-image-name: shippingService.image.repository
#     argocd-image-updater.argoproj.io/service11.helm-tag-name: shippingService.image.tag
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/M-Samii/microservices-demo.git
#     targetRevision: HEAD
#     path: helm-chart
#     helm:
#       valueFiles:
#         - values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true










#############################################################
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-app
#   namespace: argocd
#   annotations:
#     argocd-image-updater.argoproj.io/write-back-method: argocd
#     argocd-image-updater.argoproj.io/image-list: |
#       service1=mahsamii/adservice,
#       service2=mahsamii/cartservice,
#       service3=mahsamii/checkoutservice,
#       service4=mahsamii/currencyservice,
#       service5=mahsamii/emailservice,
#       service6=mahsamii/frontend,
#       service7=mahsamii/loadgenerator,
#       service8=mahsamii/paymentservice,
#       service9=mahsamii/productcatalogservice,
#       service10=mahsamii/recommendationservice,
#       service11=mahsamii/shippingservice
#     argocd-image-updater.argoproj.io/service1.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service1.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service1.kustomize-image: mahsamii/adservice
#     argocd-image-updater.argoproj.io/service2.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service2.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service2.kustomize-image: mahsamii/cartservice
#     argocd-image-updater.argoproj.io/service3.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service3.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service3.kustomize-image: mahsamii/checkoutservice
#     argocd-image-updater.argoproj.io/service4.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service4.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service4.kustomize-image: mahsamii/currencyservice
#     argocd-image-updater.argoproj.io/service5.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service5.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service5.kustomize-image: mahsamii/emailservice
#     argocd-image-updater.argoproj.io/service6.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service6.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service6.kustomize-image: mahsamii/frontend
#     argocd-image-updater.argoproj.io/service7.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service7.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service7.kustomize-image: mahsamii/loadgenerator
#     argocd-image-updater.argoproj.io/service8.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service8.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service8.kustomize-image: mahsamii/paymentservice
#     argocd-image-updater.argoproj.io/service9.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service9.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service9.kustomize-image: mahsamii/productcatalogservice
#     argocd-image-updater.argoproj.io/service10.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service10.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service10.kustomize-image: mahsamii/recommendationservice
#     argocd-image-updater.argoproj.io/service11.allow-tags: regexp:^latest$
#     argocd-image-updater.argoproj.io/service11.update-strategy: newest-build
#     argocd-image-updater.argoproj.io/service11.kustomize-image: mahsamii/shippingservice
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/M-Samii/microservices-demo.git
#     targetRevision: HEAD
#     path: kubernetes-manifests
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true