# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-app
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/M-Samii/microservices-demo.git
#     targetRevision: HEAD
#     path: helm-chart/templates
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated: {}

##########################################################################

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-app
#   namespace: argocd
#   annotations:
#   # Argo CD Image Updater settings
#     argocd-image-updater.argoproj.io/write-back-method: argocd
#     argocd-image-updater.argoproj.io/service1.allow-tags: latest
#     argocd-image-updater.argoproj.io/service2.allow-tags: latest
#     argocd-image-updater.argoproj.io/service3.allow-tags: latest  
#     argocd-image-updater.argoproj.io/service4.allow-tags: latest
#     argocd-image-updater.argoproj.io/service5.allow-tags: latest
#     argocd-image-updater.argoproj.io/service6.allow-tags: latest
#     argocd-image-updater.argoproj.io/service7.allow-tags: latest
#     argocd-image-updater.argoproj.io/service8.allow-tags: latest
#     argocd-image-updater.argoproj.io/service9.allow-tags: latest
#     argocd-image-updater.argoproj.io/service10.allow-tags: latest
#     argocd-image-updater.argoproj.io/service11.allow-tags: latest
    


#     argocd-image-updater.argoproj.io/image-list: |
#       service1=mahsamii/adservice,
#       service2=mahsamii/cartservice,
#       service3=mahsamii/checkoutservice,
#       service4=mahsamii/currencyservice,  
#       service5=mahsamii/emailservice,
#       service6=mahsamii/frontend,
#       service7=mahsamii/loadgenerator,
#       service8=mahsamii/paymentservice,
#       service9=mahsamii/productcatalogservice,
#       service10=mahsamii/recommendationservice,
#       service11=mahsamii/shippingservice
#     argocd-image-updater.argoproj.io/service1.update-strategy: digest
#     argocd-image-updater.argoproj.io/service2.update-strategy: digest
#     argocd-image-updater.argoproj.io/service3.update-strategy: digest
#     argocd-image-updater.argoproj.io/service4.update-strategy: digest
#     argocd-image-updater.argoproj.io/service5.update-strategy: digest
#     argocd-image-updater.argoproj.io/service6.update-strategy: digest
#     argocd-image-updater.argoproj.io/service7.update-strategy: digest
#     argocd-image-updater.argoproj.io/service8.update-strategy: digest
#     argocd-image-updater.argoproj.io/service9.update-strategy: digest
#     argocd-image-updater.argoproj.io/service10.update-strategy: digest
#     argocd-image-updater.argoproj.io/service11.update-strategy: digest
   
    

# spec:
#   project: default
#   source:
#     repoURL: https://github.com/M-Samii/microservices-demo.git
#     targetRevision: HEAD
#     path: helm-chart  
#     helm:
#       valueFiles:
#         - values.yaml  
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated: {}


#################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    # Argo CD Image Updater settings
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: |
      service1=mahsamii/adservice
      service2=mahsamii/cartservice
      service3=mahsamii/checkoutservice
      service4=mahsamii/currencyservice
      service5=mahsamii/emailservice
      service6=mahsamii/frontend
      service7=mahsamii/loadgenerator
      service8=mahsamii/paymentservice
      service9=mahsamii/productcatalogservice
      service10=mahsamii/recommendationservice
      service11=mahsamii/shippingservice
    argocd-image-updater.argoproj.io/service1.allow-tags: latest
    argocd-image-updater.argoproj.io/service1.update-strategy: digest
    argocd-image-updater.argoproj.io/service2.allow-tags: latest
    argocd-image-updater.argoproj.io/service2.update-strategy: digest
    argocd-image-updater.argoproj.io/service3.allow-tags: latest
    argocd-image-updater.argoproj.io/service3.update-strategy: digest
    argocd-image-updater.argoproj.io/service4.allow-tags: latest
    argocd-image-updater.argoproj.io/service4.update-strategy: digest
    argocd-image-updater.argoproj.io/service5.allow-tags: latest
    argocd-image-updater.argoproj.io/service5.update-strategy: digest
    argocd-image-updater.argoproj.io/service6.allow-tags: latest
    argocd-image-updater.argoproj.io/service6.update-strategy: digest
    argocd-image-updater.argoproj.io/service7.allow-tags: latest
    argocd-image-updater.argoproj.io/service7.update-strategy: digest
    argocd-image-updater.argoproj.io/service8.allow-tags: latest
    argocd-image-updater.argoproj.io/service8.update-strategy: digest
    argocd-image-updater.argoproj.io/service9.allow-tags: latest
    argocd-image-updater.argoproj.io/service9.update-strategy: digest
    argocd-image-updater.argoproj.io/service10.allow-tags: latest
    argocd-image-updater.argoproj.io/service10.update-strategy: digest
    argocd-image-updater.argoproj.io/service11.allow-tags: latest
    argocd-image-updater.argoproj.io/service11.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/M-Samii/microservices-demo.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true