apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-linter-config
  namespace: argocd
data:
  config.yaml: |
    checks:
      include:
        - no-privileged-containers
        - no-readiness-probe
        - no-liveness-probe
